filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /app/logs/*.log
  fields:
    type: app_logs
  fields_under_root: true
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "lol"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "lol"
  indices:
    - index: "app-logs-%{+yyyy.MM.dd}"
      when.contains:
        fields.type: "app_logs"
